"""init db

Revision ID: 107fb417a5db
Revises: 
Create Date: 2025-02-03 05:15:20.442637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '107fb417a5db'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id_project', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_project')
    )
    op.create_table('user',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('email')
    )
    op.create_table('action',
    sa.Column('id_action', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.Column('id_project', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_project'], ['project.id_project'], ),
    sa.PrimaryKeyConstraint('id_action')
    )
    op.create_table('travel',
    sa.Column('id_travel', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('start_place', sa.String(length=50), nullable=False),
    sa.Column('return_place', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('start_municipality', sa.String(length=50), nullable=True),
    sa.Column('destination', sa.String(length=50), nullable=True),
    sa.Column('night_count', sa.SmallInteger(), nullable=True),
    sa.Column('meal_count', sa.SmallInteger(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('license_vehicle', sa.String(length=12), nullable=True),
    sa.Column('comment_vehicle', sa.Text(), nullable=True),
    sa.Column('start_km', sa.SmallInteger(), nullable=True),
    sa.Column('end_km', sa.SmallInteger(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_project', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_project'], ['project.id_project'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_travel')
    )
    op.create_table('expense',
    sa.Column('id_expense', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('id_travel', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_travel'], ['travel.id_travel'], ),
    sa.PrimaryKeyConstraint('id_expense')
    )
    op.create_table('user_action',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_action', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_action'], ['action.id_action'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_user', 'id_action')
    )
    op.create_table('user_action_time',
    sa.Column('id_user_action_time', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('duration', sa.Numeric(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_action', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_action'], ['action.id_action'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_user_action_time')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_action_time')
    op.drop_table('user_action')
    op.drop_table('expense')
    op.drop_table('travel')
    op.drop_table('action')
    op.drop_table('user')
    op.drop_table('project')
    # ### end Alembic commands ###
