"""Add cascade delete to Action

Revision ID: 1cbc07e73ac4
Revises: 71d5d63bdcab
Create Date: 2025-02-10 09:57:59.598091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cbc07e73ac4'
down_revision: Union[str, None] = '71d5d63bdcab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
