"""change the type of some fields

Revision ID: 93af8d60f524
Revises: 107fb417a5db
Create Date: 2025-02-05 10:49:04.726884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93af8d60f524'
down_revision: Union[str, None] = '107fb417a5db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('action', 'description',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('project', 'start_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('project', 'is_archived',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('travel', 'start_municipality',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('travel', 'destination',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('travel', 'night_count',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.alter_column('travel', 'meal_count',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.alter_column('travel', 'license_vehicle',
               existing_type=sa.VARCHAR(length=12),
               nullable=False)
    op.alter_column('travel', 'start_km',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.alter_column('travel', 'end_km',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.alter_column('user', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('travel', 'end_km',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.alter_column('travel', 'start_km',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.alter_column('travel', 'license_vehicle',
               existing_type=sa.VARCHAR(length=12),
               nullable=True)
    op.alter_column('travel', 'meal_count',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.alter_column('travel', 'night_count',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.alter_column('travel', 'destination',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('travel', 'start_municipality',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('project', 'is_archived',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('project', 'start_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('action', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###
