"""Add project hours limit

Revision ID: c9813f07ad01
Revises: c94eb6d555f5
Create Date: 2026-07-03 10:06:35.341829

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c9813f07ad01"
down_revision: Union[str, None] = "c94eb6d555f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project", sa.Column("hours_limit", sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "hours_limit")
    # ### end Alembic commands ###
